name: API Request on Push or PR

on:
  push:

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer requisição HTTP
        run: |
          curl -X POST -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN2 }}" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main"}'\
            https://api.github.com/repos/vgiovanini/my-processor/actions/workflows/pull.yml/dispatches
